/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.util.*;
import javax.swing.DefaultListModel;

/**
 *
 * @author Nawaal Hanif
 */
public class GuiCollection extends javax.swing.JFrame {
    
    DefaultListModel<String> dlm;
    List<String> items = new ArrayList<>();
    String[] datas = {"buku", "meja", "kursi", "tas", "pintu"};
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GuiCollection.class.getName());

    /**
     * Creates new form GuiCollection
     */
    public GuiCollection() {
        initComponents();
        dlm = new DefaultListModel<>();
        jListItem.setModel(dlm);
        for (String data : datas) {
            dlm.addElement(data);
        }
        updateJumDataTersimpan();
    }
    
    private void updateJumDataTersimpan() {
        jLabelJumlahData.setText("Data tersimpan = " + items.size());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListItem = new javax.swing.JList<>();
        TextFieldItem = new javax.swing.JTextField();
        jLabelJumlahData = new javax.swing.JLabel();
        ButtonAddItem = new javax.swing.JButton();
        ButtonUpdate = new javax.swing.JButton();
        ButtonDelete = new javax.swing.JButton();
        ButtonClearAll = new javax.swing.JButton();
        jButtonInsertData = new javax.swing.JButton();
        btnSaveList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListItem.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListItem);

        TextFieldItem.setText("jTextField1");

        jLabelJumlahData.setText("Data tersimpan = 0");

        ButtonAddItem.setText("Add");
        ButtonAddItem.addActionListener(this::ButtonAddItemActionPerformed);

        ButtonUpdate.setText("Update");
        ButtonUpdate.addActionListener(this::ButtonUpdateActionPerformed);

        ButtonDelete.setText("Delete");
        ButtonDelete.addActionListener(this::ButtonDeleteActionPerformed);

        ButtonClearAll.setText("Clear All");
        ButtonClearAll.addActionListener(this::ButtonClearAllActionPerformed);

        jButtonInsertData.setText("Insert Data");
        jButtonInsertData.addActionListener(this::jButtonInsertDataActionPerformed);

        btnSaveList.setText("Save to List");
        btnSaveList.addActionListener(this::btnSaveListActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextFieldItem, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelJumlahData))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonAddItem)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonClearAll))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonInsertData))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaveList)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelJumlahData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonAddItem)
                            .addComponent(ButtonClearAll))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonUpdate)
                            .addComponent(jButtonInsertData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonDelete)
                            .addComponent(btnSaveList))))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddItemActionPerformed
        dlm.addElement(TextFieldItem.getText());
        TextFieldItem.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAddItemActionPerformed

    private void ButtonClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClearAllActionPerformed
        dlm.clear();// TODO add your handling code here:
    }//GEN-LAST:event_ButtonClearAllActionPerformed

    private void jButtonInsertDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertDataActionPerformed
        for (String item : datas) {
            dlm.addElement(item);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButtonInsertDataActionPerformed

    private void ButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUpdateActionPerformed
        int index = jListItem.getSelectedIndex();
    dlm.setElementAt(TextFieldItem.getText(), index);
    TextFieldItem.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonUpdateActionPerformed

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
        int index = jListItem.getSelectedIndex();
        dlm.removeElementAt(index);
        TextFieldItem.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private void btnSaveListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveListActionPerformed
        items.clear();
        for (int i = 0; i < dlm.getSize(); i++) {
            items.add(dlm.getElementAt(i));
        }
        updateJumDataTersimpan();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GuiCollection().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAddItem;
    private javax.swing.JButton ButtonClearAll;
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonUpdate;
    private javax.swing.JTextField TextFieldItem;
    private javax.swing.JButton btnSaveList;
    private javax.swing.JButton jButtonInsertData;
    private javax.swing.JLabel jLabelJumlahData;
    private javax.swing.JList<String> jListItem;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
